version: '3.8'
services:
  app:
    image: image
    ports:
      - "8000:8000"
    environment:
      - EVENT_NAME=EVENT_NAME
      - S3_ENDPOINT=minio:9000
      - S3_ACCESS_KEY=ROOTNAME
      - S3_SECRET_KEY=CHANGEME123
      - S3_BUCKET=event1
      - SHOW_ONLY_OWN_PHOTOS=false
    depends_on:
      - minio


  minio:
    image: quay.io/minio/minio
    container_name: minio
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      - MINIO_ROOT_USER=ROOTNAME
      - MINIO_ROOT_PASSWORD=CHANGEME123
    command: server /data --console-address ":9001"
    volumes:
      - ./minio_data:/data
