version: '3.8'
services:
  app:
    image: sysm0n/snapshare:latest
    ports:
      - "8000:8000"
    environment:
      - EVENT_NAME=Event Name
      - S3_ENDPOINT=minio:9000
      - S3_ACCESS_KEY=ROOTNAME
      - S3_SECRET_KEY=CHANGEME123
      - S3_BUCKET=event1
      - SHOW_ONLY_OWN_PHOTOS=false
      - USE_BACKGROUND=true
    depends_on:
      - minio
    volumes:
      - ./background.svg:/app/background.svg

  minio:
    image: quay.io/minio/minio
    container_name: minio
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      - MINIO_ROOT_USER=ROOTNAME
      - MINIO_ROOT_PASSWORD=CHANGEME123
    command: server /data --console-address ":9001"
    volumes:
      - ./minio_data:/data
